// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SqlliteRepositories.Model;
using System;

namespace SqlliteRepositories.Migrations
{
    [DbContext(typeof(OffchainMonitorContext))]
    [Migration("20170902132823_CommitmentTxIdAdded")]
    partial class CommitmentTxIdAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SqlliteRepositories.Model.CommitmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commitment");

                    b.Property<int?>("CommitmentOutputOutputNumber");

                    b.Property<string>("CommitmentOutputTransactionId");

                    b.Property<string>("CommitmentTxId");

                    b.Property<string>("Punishment");

                    b.HasKey("Id");

                    b.HasIndex("CommitmentOutputTransactionId", "CommitmentOutputOutputNumber");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("SqlliteRepositories.Model.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Component");

                    b.Property<string>("Context");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Level");

                    b.Property<string>("Msg");

                    b.Property<string>("Process");

                    b.Property<string>("Stack");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("SqlliteRepositories.Model.MultisigOutputEntity", b =>
                {
                    b.Property<string>("TransactionId");

                    b.Property<int>("OutputNumber");

                    b.Property<DateTime>("LastSeen");

                    b.HasKey("TransactionId", "OutputNumber");

                    b.ToTable("MultisigOutputs");
                });

            modelBuilder.Entity("SqlliteRepositories.Model.SettingsEntity", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SqlliteRepositories.Model.CommitmentEntity", b =>
                {
                    b.HasOne("SqlliteRepositories.Model.MultisigOutputEntity", "CommitmentOutput")
                        .WithMany("Commitments")
                        .HasForeignKey("CommitmentOutputTransactionId", "CommitmentOutputOutputNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
